#!/bin/sh
for file in jars/*.jar; do
    jars=$jars:$file
done

classpath=app:$jars:lib

if which rlwrap > /dev/null
then
    rlwrap java -cp $classpath clojure.lang.Repl app/$1.clj
else
    java -cp $classpath jline.ConsoleRunner clojure.lang.Repl app/$1.clj
fi
