#!/bin/sh

cd `dirname $0`/..

for file in jars/*.jar; do
    jars=$jars:$file
done

classpath=app:$jars:lib

if which rlwrap > /dev/null
then
    rlwrap java -cp $classpath clojure.lang.Repl boot/boot.clj
else
    java -cp $classpath jline.ConsoleRunner clojure.lang.Repl boot/boot.clj
fi
