#!/bin/sh
for file in jars/*.jar; do
    jars=$jars:$file
done

classpath=app:$jars:lib/contrib:lib/compojure

if which rlwrap > /dev/null
then
    rlwrap java -cp $classpath clojure.lang.Script config/boot.clj
else
    java -cp $classpath jline.ConsoleRunner clojure.lang.Script config/boot.clj
fi
