#!/bin/bash

if [ $(uname | cut -c -6) = 'CYGWIN' ]
then
    EXT="$(find deps -mindepth 1 -maxdepth 1 | xargs cygpath -aw | tr \\n \;)"
    CLASSPATH="$EXT;$(cygpath -aw src);$(cygpath -aw .)"
else
    EXT="$(find deps -mindepth 1 -maxdepth 1 -print0 | tr \\0 \:)"
    CLASSPATH="$EXT:src:."
fi

export CLASSPATH

java clojure.lang.Script test/run.clj 
